version: '3.8'

services:
  app:
    build:
      context: .
    container_name: app-login
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/login
      - SPRING_DATASOURCE_USERNAME=anselmo
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=anselmo
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=login
    ports:
      - "5432:5432"
